services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:80"  # 本番用のApacheポート（公開）
      - "3000:3000"  # 開発用のReactホットリロード（開発用に制限）
    volumes:
      - ./app:/var/www/html
      - ./docker/app/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/app/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      db:
        condition: service_healthy  # MySQL が起動するのを待つ
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    networks:
      - laravel_react
    command: >
      bash -c "npm install && npm run hot"  # ホットリロードを有効にするコマンド

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - laravel_react
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8001:80"  # PhpMyAdmin は外部公開
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - laravel_react

# volumes:
#   mysql_data:

networks:
  laravel_react:
    driver: bridge
