FROM mysql:8.0

# MySQL の設定をコピー
# COPY ./mysql/my.cnf /etc/mysql/my.cnf

# MySQL の環境変数
ENV MYSQL_DATABASE=laravel_db
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
